// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMVapiV2.Models
{
    public partial class Dmvworker
    {
        public Dmvworker()
        {
            DriverVehicles = new HashSet<DriverVehicle>();
        }

        public int WorkerId { get; set; }
        public string WorkersFirstName { get; set; }
        public string WorkersLastName { get; set; }
        public string WorkersUserName { get; set; }
        public string WorkersPassword { get; set; }

        public virtual ICollection<DriverVehicle> DriverVehicles { get; set; }
    }
}