// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMVapiV2.Models
{
    public partial class DriverVehicle
    {
        public int DriverVehicleId { get; set; }
        public string DriversSocialSecurity { get; set; }
        public string Vin { get; set; }
        public int? WorkerId { get; set; }

        public virtual Driver DriversSocialSecurityNavigation { get; set; }
        public virtual Vehicle VinNavigation { get; set; }
        public virtual Dmvworker Worker { get; set; }
    }
}