// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMVapiV2.Models
{
    public partial class Driver
    {
        public Driver()
        {
            DriverVehicles = new HashSet<DriverVehicle>();
            Infractions = new HashSet<Infraction>();
        }

        public string DriverSocialSecurity { get; set; }
        public string DriversFirstName { get; set; }
        public string DriversLastName { get; set; }
        public string DriversPhoneNumber { get; set; }
        public string DriversStreetAddress { get; set; }
        public string DriversCity { get; set; }
        public string DriversState { get; set; }
        public int? DriversZipCode { get; set; }
        public int? DriversAge { get; set; }

        public virtual ICollection<DriverVehicle> DriverVehicles { get; set; }
        public virtual ICollection<Infraction> Infractions { get; set; }
    }
}