// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMVapiV2.Models
{
    public partial class Officer
    {
        public Officer()
        {
            Infractions = new HashSet<Infraction>();
        }

        public int BadgeNumber { get; set; }
        public string OfficerFirstName { get; set; }
        public string OfficerLastName { get; set; }
        public string PoliceUsername { get; set; }
        public string PolicePassword { get; set; }

        public virtual ICollection<Infraction> Infractions { get; set; }
    }
}