// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMVapiV2.Models
{
    public partial class Vehicle
    {
        public Vehicle()
        {
            DriverVehicles = new HashSet<DriverVehicle>();
        }

        public string Vin { get; set; }
        public string LicensePlate { get; set; }
        public string Make { get; set; }
        public string Model { get; set; }
        public string Color { get; set; }
        public string ModelYear { get; set; }

        public virtual ICollection<DriverVehicle> DriverVehicles { get; set; }
    }
}